// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-J7Am94y1jkeiTeiVzkyVCe1vUb28bc',
    appId: '1:870823498443:web:3865a560b3b36f0d3bc14e',
    messagingSenderId: '870823498443',
    projectId: 'aisyiyah-smart-life',
    authDomain: 'aisyiyah-smart-life.firebaseapp.com',
    storageBucket: 'aisyiyah-smart-life.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhfCvEaZG7_xitsChK4t-d3Xo7nvLysQ',
    appId: '1:870823498443:android:4feeea54db93e5a03bc14e',
    messagingSenderId: '870823498443',
    projectId: 'aisyiyah-smart-life',
    storageBucket: 'aisyiyah-smart-life.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0VE8FmYcx3mK2KppOasapRkKv44biTs',
    appId: '1:870823498443:ios:4c8e536d191964c73bc14e',
    messagingSenderId: '870823498443',
    projectId: 'aisyiyah-smart-life',
    storageBucket: 'aisyiyah-smart-life.firebasestorage.app',
    iosClientId: '870823498443-h28c0acqf4k1f4mc7vgvloer9s50ivi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisyiyahSmartlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0VE8FmYcx3mK2KppOasapRkKv44biTs',
    appId: '1:870823498443:ios:4c8e536d191964c73bc14e',
    messagingSenderId: '870823498443',
    projectId: 'aisyiyah-smart-life',
    storageBucket: 'aisyiyah-smart-life.firebasestorage.app',
    iosClientId: '870823498443-h28c0acqf4k1f4mc7vgvloer9s50ivi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisyiyahSmartlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-J7Am94y1jkeiTeiVzkyVCe1vUb28bc',
    appId: '1:870823498443:web:7cd64a6365109be83bc14e',
    messagingSenderId: '870823498443',
    projectId: 'aisyiyah-smart-life',
    authDomain: 'aisyiyah-smart-life.firebaseapp.com',
    storageBucket: 'aisyiyah-smart-life.firebasestorage.app',
  );

}